### ISSUE TITLE
Inappropriate use of valid domains

### ISSUE THREAD

**Issue by gorticus** [jennybc/send-email-with-r#1]
# Request

Please remove the valid domains in your example; recommendation follows.

# Context
As an owner of one of the domains you used in this repo, I do not welcome the additional spam that will result from this.  It's already forked 4x, and indexed by google, so its not only fair game for your students but anyone that scrapes addresses for spam purposes.  While it may be fine to test with your own set of addresses for validation, if you are trying to teach people how to send spam from R, a brief check of [IANA's reserved domains page](http://www.iana.org/domains/reserved) would have provided the info on how to use the standard `example.com` and `example.org` domains for *illustrative* purposes:

> ## Example domains
>
> As described in [RFC 2606](http://www.iana.org/go/rfc2606) and [RFC 6761](http://www.iana.org/go/rfc6761), a number of domains such as `example.com` and `example.org` are maintained for documentation purposes. These domains may be used as illustrative examples in documents without prior coordination with us. They are not available for registration transfer.

# Recommendation

Insert `.example` between your `NAME` and `.org`, e.g., `shire.example.org`.

**Comment by jennybc** [comment]
Sorry about this. Will do this now.

**Comment by gorticus** [comment]
Thank you.

Recommend following GitHub's [removing sensitive data](https://help.github.com/articles/remove-sensitive-data/) guide.

Any chance the 4 forks are your students?  If not, I'll post issues there, and link to this issue.

**Comment by jennybc** [comment]
Sorry again. This is pure ignorance on my part. I think I've got your recommendation implemented everywhere now.

One of the forks is one of my TAs. I don't recognize the other three users.

And yes now I will follow your link to removing sensitive data.

**Comment by jennybc** [comment]
@gorticus 

The commit history really didn't matter, so I just nuked it and did a force push. Seemed simpler than the more surgical approach needed for re: sensitive data in a specific file.
