### ISSUE TITLE
How would you apply the `html_body` function with the frame work you set up?

### ISSUE THREAD

**Issue by johnhenrypezzuto** [jennybc/send-email-with-r#14]
Hi Jenny,

Thank you for this tutorial! It has been really helpful. I was wondering if you could help me out with what I think is a pretty easy question. How would you apply the `gmailr::html_body` function to the framework you use (shown below)? The first argument of the `html_body` function is the `mime` so I think it would need to be the last step (placing it inside the mutate causes an error). I think this probably a pretty easy purrr question, but I wasn't able to figure it out.

```
emails <- email_list %>%
    mutate(
        To = Email,
        From = my_email,
        Subject = subject,
        body = sprintf(body, `First Name`, `Last Name`)) %>%
    select(To, From, Subject, body) %>% 
    pmap(mime)
```

Thanks again!

**Comment by jennybc** [comment]
Off the top of my head, I'm not sure. I've never needed to use that.

I have vague memories of seeing others struggle with the html_body in general, so perhaps there is some actual problem (as in bug) with that?

This project obviously uses the html_body, so maybe it has some good, working code for inspiration:

https://github.com/ropenscilabs/ponyexpress

**Comment by johnhenrypezzuto** [comment]
For future reference, I was able to figure this out from a solution  to a [similar problem from the rstudio community website](https://community.rstudio.com/t/embedding-hyperlinks-in-the-text-of-a-gmailr-message/6430/3).

The trick is to change the ```pmap(mime)``` to ```pmap(mime, attr = list(content_type = "text/html"))```
