### ISSUE TITLE
Download icon for JSON file missing

### ISSUE THREAD

**Issue by pathmes** [jennybc/send-email-with-r#16]
Hi,

I am trying to setup Gmailr.  I enabled Gmail API and I think I have created the credentials but there is no download icon to download the JSON file - only visible icons are copy, edit & trash.. 
![api](https://user-images.githubusercontent.com/11284640/125158556-9a494c80-e18f-11eb-9a30-2fd014dc1824.png)
Please help.  I am reasonably ok with R and RStudio, but API, credentials etc. are a big hurdle.

**Comment by jennybc** [comment]
You seem to have created an API key, not an OAuth 2.0 Client ID.

![google-cred-configure](https://user-images.githubusercontent.com/599454/130873601-9db70977-3e3b-4643-b6e8-a9105cf5da43.png)
