### ISSUE TITLE
understanding purrr::map_rows()

### ISSUE THREAD

**Issue by jennybc** [jennybc/send-email-with-r#2]
@lionel-

Will you look at my `purrr::map_rows()` usage near the end of [README](https://github.com/jennybc/send-email-with-r/blob/master/README.md) or [send-email-with-r.R](https://github.com/jennybc/send-email-with-r/blob/master/send-email-with-r.R) ...

1. Is there a better way to get a decent name for the new variable? I don't want it to be named `.out`.

2. Why do I get a second unnamed variable that is `NULL`?

**Comment by lionel-** [comment]
2. must be a bug, I'll look into it.

For 1, I guess I should add a `.out = ".out"` option to rows-based functions.

Also, I was wondering if `.labels` is really useful. Maybe it should be an option to decide whether to get the output directly or as a column of the original data frame. Could be called `.preserve` or `.enclose`. This way you don't have to extract the `.out` column.

What about `.enclose = "my_col"` to set both at the same time? When `FALSE`, get the results directly.

**Comment by lionel-** [comment]
On the other hand, it may not be desirable to have the output type vary as a function of arguments. And in this case you can simply do `edat %>% map_n(mime)`.

**Comment by jennybc** [comment]
I think `.out = ".out"` would be nice.

Thanks for telling me I don't need `lift()` there. Got it.

I don't really have an informed opinion about the other stuff yet. In my specific example, it seems fine to isolate the newly created output "by hand". I could have put that step into the pipeline but chose not to, because I wanted to reveal the creation of the puzzling NULL variable, so I could ask this question.
