### ISSUE TITLE
r console error to install gmailr package 

### ISSUE THREAD

**Issue by kapilbahal** [jennybc/send-email-with-r#4]
please help me to send bulk emails to my clients using R language, in your article i am stuck at installing packages in r console, ....i am beginer to r language experimenting with it

**Comment by jennybc** [comment]
It sounds like you'd benefit from a general introduction to R before tackling this email task. It's not a good choice as anyone's first usage of R.

I hear very good things about DataCamp's Introduction to R  course and I'm pretty sure that specific course is free:

https://www.datacamp.com

**Comment by kapilbahal** [comment]
Hi

Already done with this datacamp course and now i am studying a online book
"R for data science" and practicing on R studio.

I tried sending email using R because i want to get some practical
experience, i want to be capable enough with knowledge so that i can
compete completions on kaggle.

I also planned to do one project on data science in my Furniture
manufacturing company.

Can you please be a mentor for me ? please.....

Thanks
Kapil Bahl - 08975851505
