### ISSUE TITLE
unable to send an attachement

### ISSUE THREAD

**Issue by jhawakshay** [jennybc/send-email-with-r#5]
Hi, 

I followed all the steps to send an email from R and I am able to do it.
But if I try to send an attachment it doesn't go and throws error.

Below is the code I am using:

library(curl)
library(openssl)
library(httpuv)

suppressPackageStartupMessages(library(gmailr))
getwd()
use_secret_file("test-email.json")

test_email <- mime(
  To = "**********@gmail.com",
  From = "*********@gmail.com",
  Subject = "this is just a gmailr test",
  body = "Can you hear me now?")
  attach_file(mime("C:\\Users\\AJ\\Documents\\test.jpeg",type=jpeg))
send_message(test_email)

**Comment by jennybc** [comment]
This is a usage question or maybe an issue (?) for the [gmailr package](https://github.com/jimhester/gmailr). Yeah, attachments are definitely beyond the scope of my simple script.

**Comment by jhawakshay** [comment]
Thanks Jenny for your response.
 I really appreciate your help and understand the limitations of your script.

Could you also help me in sending an email from my Outlook email id to another Outlook email id?

Here is the code I am using: 
[library(RDCOMClient)
## init com api
OutApp <- COMCreate("Outlook.Application")
## create an email 
outMail = OutApp$CreateItem(0)
## configure  email parameter 
outMail[["To"]] = "de...@dest.com"
outMail[["subject"]] = "some subject"
outMail[["body"]] = "some body"
## send it                     
outMail$Send()


Error: I am getting:

Error: Operation aborted
Enter a frame number, or 0 to exit
1. outMail$Send()
2. .COM(x, name,.....)
3. COMStop("Operation aborted", -2147467260)

<checkErrorInfo> 80004004 
No support for InterfaceSupportsErrorInfo
checkErrorInfo -2147467260
Error: Exception occurred.

Could you please help me in this issue?
