### ISSUE TITLE
Gmail API error: 413

### ISSUE THREAD

**Issue by MST2803** [jennybc/send-email-with-r#6]
Hi Jenny,

thanks for the very nice examples! Very helpful.

I have a new issue with files (xlsx) with a size of 15MB i want to send.

I am receiving following response:

`Error in gmailr_POST(c("messages", "send"), user_id, class = "gmail_message",  : 
  Gmail API error: 413
  
In addition: Warning message:
In stop(cond, call. = FALSE) : additional arguments ignored in stop()`

Is there any way I can overcome this problem?

**Comment by MST2803** [comment]
![image](https://user-images.githubusercontent.com/31045488/29329298-bdcfa5d0-81f5-11e7-9134-d686fe412972.png)

**Comment by jennybc** [comment]
Looks like 15MB is to big for the method gmailr is using:

https://stackoverflow.com/questions/24462184/413-request-entity-too-large

You could open an issue there? As a practical matter, that file might be a good candidate to put somewhere and just share a link.
