### ISSUE TITLE
Encoding Error

### ISSUE THREAD

**Issue by msgoussi** [jennybc/send-email-with-r#7]
I created a user defined function using your function send_message
email.message <- function(body){
  gmailr::send_message(mime(from = "xxx@gmail.com",
                            to = "xxx@gmail.com",
                            subject = "R Progress",
                            body = body)) 
  }
if run in R: email.message(basename(rstudioapi::getSourceEditorContext()$path)), I get this error,
Error in `Encoding<-`(`*tmp*`, value = "UTF-8") : 
  a character vector argument expected

Would you please advice.
Thanks

**Comment by jennybc** [comment]
This might be something you should take up in the [gmailr repo](https://github.com/jimhester/gmailr).

Also what does it have to do with the rstudioapi package? Feels like there's more to this story.

In any case, this repo was just meant to document my workflow for sending lots of email with gmailr. I can't provide general usage advice for it here.
