### ISSUE TITLE
force the auth process explicitly via gmail_auth()

### ISSUE THREAD

**Issue by mmadmar** [jennybc/send-email-with-r#8]
Dear all

I am trying to reauthenticate (in order to use a different gmail account) by using gmail_auth().
But the authentication process does start when executing gmail_auth().

What am I doing wrong?

Many thanks

**Comment by jennybc** [comment]
Do you perhaps need to delete an existing `.httr-oauth` file? Note the leading dot will make it hidden in many of the ways you normally view files.

**Comment by mmadmar** [comment]
I was not able to find the` .httr-oauth` file. But (for an unknown reason) the script asked me to authenticate an I was able to use the correct gmail account.
Thanks!
